### ISSUE TITLE
Proposal: Package name change

### ISSUE THREAD

**Issue by jshthornton** [eXon/react-cookie#37]
Just wanted to start off with saying this is a great minimal cookie library, but that is exactly what it is, just a cookie library. It doesn't have anything to do with React?

For the sake of making this package more accessible universally can I suggest that the package be renamed to something which doesn't include a framework.

**Comment by eXon** [comment]
The reason why this library is react-cookie and not just cookie is because it is specifically targeting the needs of React developers with server-rendering. Of course you can use react-cookie with any framework. There is probably 1000 libraries available for that.

Do you have a suggestion for a better name?

**Comment by jshthornton** [comment]
I understand why. It's a good reason, but could be applied to any server that uses nodejs to serve up the frontend. If this library was intended to work isomorphically, then maybe just call it that? isomorphic-cookie

**Comment by eXon** [comment]
The name will not change but thank you for proposing it :)
